services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: elacode
      POSTGRES_PASSWORD: elacodepassword
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

  elacode-api:
    container_name: elacode-api
    image: elviramjeshtri/elacode-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - 8085:8082
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

  elacode-react:
    container_name: elacode-react
    image: elviramjeshtri/elacode-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8085
    ports:
      - "3000:5173"
    depends_on:
      - elacode-api
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: