server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    username: elvira
    password: elvira
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    user: elvira
    password: elvira
    url: jdbc:postgresql://localhost:5432/customer
  main:
    web-application-type: servlet
