server:
  port: 8082
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    username: elacode
    password: elacodepassword
    url: jdbc:postgresql://awseb-e-hwgrikfd25-stack-awsebrdsdatabase-jacyjlcfigfe.ciymfer2wzfz.eu-north-1.rds.amazonaws.com:5432/ebdb
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
  main:
    web-application-type: servlet
