server:
  port: 8082
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    username: elacode
    password: elacodepassword
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
  main:
    web-application-type: servlet
